apiVersion: apps/v1
kind: Deployment
metadata:
  name: chaos-panel
  namespace: demo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chaos-panel
  template:
    metadata:
      labels:
        app: chaos-panel
    spec:
      containers:
        - name: chaos-panel
          image: demo-chaos-panel:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8888
---
apiVersion: v1
kind: Service
metadata:
  name: chaos-panel
  namespace: demo-app
spec:
  selector:
    app: chaos-panel
  ports:
    - port: 8888
      targetPort: 8888
  type: LoadBalancer
